basePath: /api/
host: localhost:8080
info:
  contact:
    name: Rinat Almakhov
    url: https://github.com/Gasoid/
  description: app downloads photos from vk.
  license:
    name: MIT License
    url: https://github.com/Gasoid/photoDumper/blob/main/LICENSE
  title: PhotoDumper
  version: 1.1.2
paths:
  /albums/{sourceName}/:
    get:
      consumes:
      - application/json
      description: returns albums
      parameters:
      - description: source name
        in: path
        name: sourceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: error
          schema:
            type: string
        "401":
          description: error
          schema:
            type: string
        "403":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Albums
  /download-album/{albumID}/{sourceName}/:
    get:
      consumes:
      - application/json
      description: download all photos of particular album, returns destination of
        your photos
      parameters:
      - description: source name
        in: path
        name: sourceName
        required: true
        type: string
      - description: album ID
        in: path
        name: albumID
        required: true
        type: string
      - description: directory where photos will be stored
        in: query
        name: dir
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: error
          schema:
            type: string
        "401":
          description: error
          schema:
            type: string
        "403":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: download photos of album
  /download-all-albums/{sourceName}/:
    get:
      consumes:
      - application/json
      description: download all photos of all albums, returns destination of your
        photos
      parameters:
      - description: source name
        in: path
        name: sourceName
        required: true
        type: string
      - description: directory where photos will be stored
        in: query
        name: dir
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: error
          schema:
            type: string
        "401":
          description: error
          schema:
            type: string
        "403":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: download photos of albums
  /sources/:
    get:
      consumes:
      - application/json
      description: returns sources
      produces:
      - application/json
      responses:
        "200":
          description: sources
          schema:
            items:
              type: string
            type: array
      summary: Sources
securityDefinitions:
  ApiKeyAuth:
    in: query
    name: api_key
    type: apiKey
swagger: "2.0"
